debug: true
db:
  path: /data/juicebot.db
dogConfig:
  dogEmote:
calloutConfig:
  calloutGuilds:
  - <guild_id>
  calloutMessages:
  - <message>
  calloutChance: 1500
games:
  channels:
  - guildid: <guild_id>
    channelid: <channel_id>
